services:
  - type: web
    name: nomad
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PUBLIC_ORIGIN
        value: https://nomad-en95.onrender.com
